export const contactsActionTypes = {
    CHANGE_SEARCH_VALUE: "CHANGE_SEARCH_VALUE",
    REMOVE_CONTACT: "REMOVE_CONTACT",
    ADD_CONTACT: "ADD_CONTACT",
    ADD_OR_REMOVE_EDIT_MODUS: "ADD_OR_REMOVE_EDIT_MODUS",
    TOOGLE_VISIBLE_MODAL: "TOOGLE_VISIBLE_MODAL"
};